version: '3.1'
services:
  web:
    image: odoo:16
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - /C/Users/dani/Desktop/odoo/odooodoo-web-data:/var/lib/odoo
      - /C/Users/dani/Desktop/odoo/config:/etc/odoo
      - /C/Users/dani/Desktop/odoo/addons:/mnt/extra-addons
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
